/*
 * This source file was generated by the Gradle 'init' task
 */
package jdbc.mysql;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;

import org.flywaydb.core.Flyway;

import jdbc.mysql.persistence.EmployeeDAO;
import jdbc.mysql.persistence.entity.EmployeeEntity;

public class Main {
    public static void main(String[] args) {
        var flyway = Flyway.configure()
            .dataSource("jdbc:mysql://localhost/jdbc-sample", "root", "root")
            .load();
        flyway.migrate();
        ;

        EmployeeEntity employee = EmployeeDAO.findById(3);
        EmployeeDAO.delete(employee);
    }
}
