/*
 * This source file was generated by the Gradle 'init' task
 */
package jdbc.mysql;

import org.flywaydb.core.Flyway;

public class Main {
    public static void main(String[] args) {
        var flyway = Flyway.configure()
            .dataSource("jdbc:mysql://localhost/jdbc-sample", "root", "root")
            .load();
        flyway.migrate();
    }
}
